"""empty message

Revision ID: 2202bf56078c
Revises: 28bdc244fe69
Create Date: 2018-03-09 19:32:53.642158

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2202bf56078c"
down_revision = "28bdc244fe69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("deleted", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "deleted")
    # ### end Alembic commands ###
