"""Add created index

Revision ID: 2d01a355c380
Revises: 745ca8284c1e
Create Date: 2020-10-22 17:39:17.650030

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d01a355c380"
down_revision = "745ca8284c1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("message_created_idx", "message", ["created"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("message_created_idx", table_name="message")
    # ### end Alembic commands ###
