"""empty message

Revision ID: 3c8ba8adfa5c
Revises: 2202bf56078c
Create Date: 2018-03-09 19:47:29.504579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c8ba8adfa5c"
down_revision = "2202bf56078c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "error_code", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "message", "error_message", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("message", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "message", "error_message", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("message", "error_code", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
