"""empty message

Revision ID: f5c5ab61577c
Revises: 3c8ba8adfa5c
Create Date: 2018-03-19 14:58:12.361996

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5c5ab61577c"
down_revision = "3c8ba8adfa5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("date_sent", sa.String(), nullable=True))
    op.add_column("message", sa.Column("twilio_sid", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "twilio_sid")
    op.drop_column("message", "date_sent")
    # ### end Alembic commands ###
